[package]
name = "secp256r1"
version = "0.1.0"
edition = "2024"

[dependencies]
hmac = "0.12"
rand_core = { version = "0.6", features = ["getrandom"] }
sha2 = "0.10"
zeroize = "1.8"

[dev-dependencies]
criterion = "0.5"
openssl = "0.10"
p256 = { version = "0.13", features = ["ecdsa", "expose-field"] }

[[bench]]
name = "verify"
harness = false

[[bench]]
name = "field"
harness = false

[[bench]]
name = "group"
harness = false

[[bench]]
name = "scalar"
harness = false

[[bench]]
name = "sign"
harness = false
